### ISSUE TITLE
Panic in release mode due to missing `OpenXRBindingModifierEditor` APIs

### ISSUE THREAD

**Issue by aekobear** [godot-rust/gdext#1067]
If I create the Hello World "spinning godot icon" app using the latest gdext library:

```toml

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
```
The game runs perfectly in editor, but when I try to run the game as an executable after exporting it, the game immediately crashes with an error:

>ERROR: Parameter "mb" is null.
   at: gdextension_classdb_get_method_bind (core/extension/gdextension_interface.cpp:1617)
>ERROR: Rust function panicked: [panic]
  Failed to load class method OpenXRBindingModifierEditor::get_binding_modifier (hash 2930765082).
  Make sure gdext and Godot are compatible: https://godot-rust.github.io/book/gdext/advanced/compatibility.html
  at /home/aekobear/.cargo/git/checkouts/gdext-067f4b88e7bd088f/da23b37/godot-ffi/src/toolbox.rs:352
  Context: failed to initialize GDExtension level `Scene`
   at: godot_core::private::handle_panic_with_print (/home/aekobear/.cargo/git/checkouts/gdext-067f4b88e7bd088f/da23b37/godot-core/src/private.rs:404)

When I change my `Cargo.toml` to point at the latest release of gdext:

```toml

[dependencies]
godot = "*"
```

then exporting the project works fine.

I am testing this on the latest stable godot version (4.4.stable.official.4c311cbee)
