### ISSUE TITLE
0.2.4 release seems to have broken signal codegen

### ISSUE THREAD

**Issue by tylersaunders** [godot-rust/gdext#1170]
tldr; It seems the `#[signal]` related codegen in the 0.2.4 release seems to not work as expected.

Following the [Hello, World!](https://godot-rust.github.io/book/intro/hello-world.html) example, I extended the sample class to include a signal:

```toml
# cargo.toml
[package]
name = "game"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = "0.2.4"
```

```rust
// lib.rs

use godot::{classes::{ISprite2D, Sprite2D}, prelude::*};

struct Game;

#[gdextension]
unsafe impl ExtensionLibrary for Game {}

#[derive(GodotClass)]
#[class(base=Sprite2D)]
struct Player {
    speed: f64,
    angular_speed: f64,
    base: Base<Sprite2D>,
}

#[godot_api]
impl Player {

    // BEGIN modified code
    #[signal]
    fn spin();

    fn on_spin(&mut self) {
        godot_print!("signal!");
    }
   // END
}

#[godot_api]
impl ISprite2D for Player {
    fn init(base: Base<Sprite2D>) -> Self {
        godot_print!("Hello, world!");

        Self {
            speed: 400.0,
            angular_speed: std::f64::consts::PI,
            base,
        }
    }

    fn ready(&mut self) {
        self.signals().spin().connect_self(Self::on_spin);
    }

    fn physics_process(&mut self, delta: f64) {
        let radians = (self.angular_speed * delta) as f32;
        self.base_mut().rotate(radians);
    }
}

```

```shell
> cargo build
Compiling game v0.1.0 (...)
error[E0599]: no method named `signals` found for mutable reference `&mut Player` in the current scope
  --> src/lib.rs:40:14
   |
40 |         self.signals().spin().connect_self(Self::on_spin);
   |              ^^^^^^^ method not found in `&mut Player`

```

However, when I pull the latest from `master` branch the above code compiles without issue.

```toml
# cargo.toml
[package]
name = "game"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
```
