### ISSUE TITLE
`Variant` Parameter and Return Type Shows Up as `(no base)`

### ISSUE THREAD

**Issue by Dheatly23** [godot-rust/gdext#159]
I have method with complex multiple dispatch of arguments and maybe empty return value. Since `Option<T>` is not supported as parameters nor return value, i use `Variant` as workaround.

Example:
```rust
#[func]
fn method(&self, arg0: Variant) -> Variant {
    // ...
}
```

But when i call it in GDScript, it errors with:
```
Line [XXX]: Cannot get return value of call to "method()" because it returns "void".
```

When i checked into it's documentation i saw this in methods section:
```
(no base) method(arg0: (no base))
```

Is this normal? I can't call it since it returns "void" even though it's not.

**Comment by sayaks** [comment]
does the class you're defining method on have a `base` field? could you show the class struct either way?

**Comment by Dheatly23** [comment]
Yes the class have `base` field. I can't exactly whip up a minimal example right now, but it's in (interim) port of my addon.

**Comment by Bromeon** [comment]
I wonder if this has been introduced with #147.

@Dheatly23 could you check if this also occurs with a revision before that was merged?
```toml
[dependencies]
godot = { git = "https://github.com/godot-rust/gdextension", rev = "7d42ebb425ada12459ca810e39f4277d6ddefd32" }
```
