### ISSUE TITLE
Gdext not reading environment variable 'GODOT4_BIN'

### ISSUE THREAD

**Issue by AskSkivdal** [godot-rust/gdext#183]
Os: ```fedora 37```
Rust version: ```v1.66.0```

Error:
```
thread 'main' panicked at 'Bindings generation requires 'godot4' executable or a GODOT4_BIN 
environment variable (with the path to the executable).', 
/home/*****/.cargo/git/checkouts/gdext-76630c89719e160c/6bfe53e/godot-codegen/src/godot_exe.rs:121:9
```

Cargo.toml:
```toml
[package]
name = "testlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master"}

[lib]
crate-type = ["cdylib"]
```

I have decleared the environment variable in ```~/.bashrc``` like this
```bash
# Bottom of file

GODOT4_BIN=/home/*****/Documents/applications/godot/stable/Godot_v4.0-stable_linux.x86_64
```
It is decleared in the terminal when i run
```
> echo $GODOT4_BIN
/home/*****/Documents/applications/godot/stable/Godot_v4.0-stable_linux.x86_64
```

When i run ```$GODOT4_BIN``` godot starts as usual.
